import functions.deferred_whole_life_insurance 
import functions.life_annuity_due 
import functions.life_immediate_annuity 
import functions.temporary_life_annuity 
import functions.Temporary_life_insurance 
import functions.whole_life_insurance 
import functions.plot_by_age
